services:
  mariadb:
    container_name: mariadb
    volumes: 
      - mariadb:/var/lib/mysql
    networks:
      - inception
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    restart: on-failure


  nginx:
    container_name: feur
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure
    expose:
      - 80

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
    - wordpress:/var/www/html
    networks:
      - inception
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    restart: on-failure
    expose:
    - 9000

volumes:
  wordpress:
    driver: local
    name: wordpress
    driver_opts:
      type: none
      o: bind
      device: /$HOME/data/wordpress
  mariadb:
    driver: local
    name: mariadb
    driver_opts:
      type: none
      o: bind
      device: /$HOME/data/mariadb

networks:
    inception:
      driver: bridge