version: "3.5"

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  wordpress:
    driver: local
    name: wordpress
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /$HOME/data/wordpress
  mariadb:
    driver: local
    name: mariadb
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /$HOME/data/mariadb

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: unless-stopped

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: unless-stopped
